### ISSUE TITLE
CM_Util::jsonEncode: fails with warning

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2235]
> E_WARNING: json_encode(): Invalid UTF-8 sequence in argument

```
#0 [internal function]: CM_ExceptionHandling_Handler_Abstract->handleErrorRaw(2, 'json_encode(): ...', '/home/example/...', 540, Array)
#1 /home/example/releases/20160616110844/vendor/cargomedia/cm/library/CM/Util.php(540): json_encode(Array, 0)
#2 /home/example/releases/20160616110844/vendor/cargomedia/cm/library/CM/Params.php(620): CM_Util::jsonEncode(Array, NULL)
#3 /home/example/releases/20160616110844/vendor/cargomedia/cm/library/CM/MongoDb/Client.php(46): CM_Params::jsonEncode(Array)
#4 /home/example/releases/20160616110844/vendor/cargomediaedia/cm/library/CM/Log/Handler/MongoDb.php(45): CM_MongoDb_Client->insert('cm_log', Array, Array)
#5 /home/example/releases/20160616110844/vendor/cargomedia/cm/library/CM/Log/Handler/Abstract.php(40): CM_Log_Handler_MongoDb->_writeRecord(Object(CM_Log_Record))
#6 /home/example/releases/20160616110844/vendor/cargomedia/cm/library/CM/Log/Handler/Layered.php(76): CM_Log_Handler_Abstract->handleRecord(Object(CM_Log_Record))
#7 /home/example/releases/20160616110844/vendor/cargomedia/cm/library/CM/Log/Handler/Layered.php(34): CM_Log_Handler_Layered->_addRecordToLayer(Object(CM_Log_Record), 0)
#8 /home/example/releases/20160616110844/vendor/cargomedia/cm/library/CM/Log/Logger.php(145): CM_Log_Handler_Layered->handleRecord(Object(CM_Log_Record))
#9 /home/example/releases/20160616110844/vendor/cargomedia/cm/library/CM/Log/Logger.php(92): CM_Log_Logger->_addRecord(Object(CM_Log_Record))
#10 /home/example/releases/20160616110844/vendor/cargomedia/cm/library/CM/ExceptionHandling/Handler/Abstract.php(104): CM_Log_Logger->addMessage('Application err...', 400, Object(CM_Log_Context_App))
#11 /home/example/releases/20160616110844/vendor/cargomedia/cm/library/CM/ExceptionHandling/Handler/Abstract.php(77): CM_ExceptionHandling_Handler_Abstract->_logException(Object(ErrorException))
#12 /home/example/releases/20160616110844/vendor/cargomedia/cm/library/CM/Bootloader.php(171): CM_ExceptionHandling_Handler_Abstract->handleException(Object(ErrorException))
#13 [internal function]: CM_Bootloader->{closure}(Object(ErrorException))
#14 {main}
```

**Comment by tomaszdurka** [comment]
@fvovan is this closable?

**Comment by fvovan** [comment]
the best way to check it is to run 
`db.cm_log.find({ createdAt : {$gt : ISODate("2016-07-08T15:00:00Z")}, "context.exception.message":/json_encode/}).count()`

**Comment by njam** [comment]
Result sent as PM

**Comment by njam** [comment]
As discussed let's sanitize all the log entry values for all affected handlers (*mongodb* and *fluentd* and *file*?).

In mongodb for records that had values in invalid encoding we'll add a key `sanitizedFields` that contains a key/value hash of all sanitized values for debugging.
`loggerNotifications: { sanitizedFields:  {key1: value, key2: value} }`

This should displayed next to the "context" in the admin.

**Comment by njam** [comment]
```
mongos> db.cm_log.count({ "exception.message" : {$regex : /json_encode/}, "createdAt" : { $gt : ISODate("2016-07-06T00:01:00Z")  }});
0
mongos> db.cm_log.count({ "loggerNotifications.sanitizedFields" : {$exists : 1}, "createdAt" : { $gt : ISODate("2016-07-06T00:01:00Z")  }});
6
```

**Comment by njam** [comment]
Thanks @fvovan !
